name: InventorySeparator

main: com.github.jikoo.inventoryseparator.InventorySeparator
version: 1.0.1
author: Jikoo
api-version: 1.13

commands:
  inventoryseparator:
    usage: /inventoryseparator reload
    permission: inventoryseparator.reload

permissions:
  inventoryseparator.ignoregamemode:
    description: Ignore gamemode forcing.
    default: false
    children:
      inventoryseparator.uselastgamemode:
        description: Use last gamemode on a per-group basis.
        default: op
  inventoryseparator.ignoreinventoryswap:
    description: Ignore inventory swapping per-gamemode and per-group.
    default: false
