name: InventorySeparator

main: com.github.jikoo.inventoryseparator.InventorySeparator
version: 1.0.0
author: Jikoo

commands:
  inventoryseparator:
    usage: /inventoryseparator reload
    permission: inventoryseparator.reload

permissions:
  inventoryseparator.ignoregamemode:
    default: false
  inventoryseparator.ignoreinventoryswap:
    default: false
